[project]
name = "hk-fastmcp"
version = "0.1.0"
description = "The fast, Pythonic way to build MCP servers and clients."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cyclopts>=5.0.0a1",
    "fastmcp[tasks]==3.0.0b2",
]
